export const MAX_ATOMIC_VIDEO_MEMBERS = 4;
export const MAX_ATOMIC_VIDEO_SOFTWARES = 4;
export const MAX_ATOMIC_VIDEO_EVENTS = 4;
export const MAX_ATOMIC_VIDEO_CUSTOM_ANSWERS = 4;
export const MAX_ATOMIC_SUBMITTED_SLOTS = 3;
